import { ATTR, RUNTIME_ATTR, type AssetEntry, type AssetMatcher, type Insets, type RasterizeManifest } from '../contract.js';

export interface CssContext {
    /** Asset directory relative to the emitted stylesheet. */
    assetDir: string;
    sliceImpl: 'border-image' | 'divs';
}

/**
 * Every rule the pipeline emits lives in one stylesheet written at build time.
 *
 * It has to be a real stylesheet rather than styles applied by the runtime: cohtml ignores
 * `<style>` elements appended after parse, so anything the runtime were to inject would
 * simply never apply. The runtime's whole job is therefore to create elements and set
 * attributes that these rules already describe.
 */
export function emitStylesheet(manifest: RasterizeManifest, ctx: CssContext): string {
    const blocks: string[] = [
        '/* Generated by vite-gameface-rasterize. Do not edit - it is rewritten on every build. */',
        '',
        `[${RUNTIME_ATTR.underlay}] {`,
        '    position: absolute;',
        '    pointer-events: none;',
        // Negative z-index paints the underlay after the element's own background but before
        // its in-flow content and text - which is exactly where a decoration layer belongs.
        '    z-index: -1;',
        '    display: block;',
        '}',
        '',
    ];

    for (const [assetId, asset] of Object.entries(manifest.assets)) {
        blocks.push(...stripRules(assetId, asset, manifest));
        blocks.push(...underlayRules(assetId, asset, manifest, ctx));
        if (asset.mode === 'element') blocks.push(...livePartRules(assetId, asset));
    }

    return blocks.join('\n') + '\n';
}

/**
 * Turns off the properties that are now in the texture. This runs against the final computed
 * set through an attribute selector rather than by editing the author's own rules, so
 * specificity never has to be reasoned about and the source CSS stays readable.
 */
function stripRules(assetId: string, asset: AssetEntry, manifest: RasterizeManifest): string[] {
    const declarations: string[] = [];

    for (const property of asset.strippedProperties) {
        switch (property) {
            case 'box-shadow':
                declarations.push('box-shadow: none !important;');
                break;
            case 'background-image':
                declarations.push('background-image: none !important;');
                break;
            case 'background-color':
                declarations.push('background-color: transparent !important;');
                break;
            case 'border-radius':
                declarations.push('border-radius: 0 !important;');
                break;
            case 'border-color':
                // The width stays: it is layout, and dropping it would move everything inside.
                declarations.push('border-color: transparent !important;');
                break;
            case 'border-image-source':
                declarations.push('border-image-source: none !important;');
                break;
            case 'filter':
                declarations.push('filter: none !important;');
                break;
            case 'mask-image':
                declarations.push('mask-image: none !important;');
                break;
        }
    }

    // Element mode empties the element: everything static became the texture, and the live parts
    // that remain are absolutely positioned. An element whose height came from those children now
    // has nothing holding it open and collapses to its padding, taking the underlay with it - so
    // the size it was captured at is pinned here. That is the fixed-box contract stated in CSS:
    // the subtree's geometry was decided at build time.
    if (asset.mode === 'element') {
        declarations.push('box-sizing: border-box;');
        declarations.push(`width: ${round(asset.captureSize.w)}px;`);
        declarations.push(`height: ${round(asset.captureSize.h)}px;`);
    }

    // The underlay is positioned against this element and painted at a negative z-index, so
    // the element has to be a positioned stacking context for it to land in the right place.
    //
    // `relative` is only correct for an element that was static. These rules are matched by
    // `div.class[data-rasterize]`, which outranks the plain `.class` selector the author
    // wrote, so emitting it unconditionally would drop every absolutely positioned decoration
    // back into flow - and in a HUD, corner-pinned panels are most of them. Any value other
    // than `static` already establishes a containing block, which is all the underlay needs.
    if ((asset.position ?? 'static') === 'static') declarations.push('position: relative;');
    declarations.push('z-index: 0;');

    return [`${selectorsFor(assetId, manifest).join(',\n')} {`, ...declarations.map((d) => `    ${d}`), '}', ''];
}

function underlayRules(assetId: string, asset: AssetEntry, manifest: RasterizeManifest, ctx: CssContext): string[] {
    const out: string[] = [];
    const { inkOverflow, borderWidths } = asset;

    // An absolutely positioned child is placed against its parent's padding box, so reaching
    // the border box edge means offsetting by the border width as well as the ink overflow.
    const inset: Insets = {
        top: inkOverflow.top + borderWidths.top,
        right: inkOverflow.right + borderWidths.right,
        bottom: inkOverflow.bottom + borderWidths.bottom,
        left: inkOverflow.left + borderWidths.left,
    };

    out.push(
        `[${RUNTIME_ATTR.underlay}="${assetId}"] {`,
        `    top: ${-inset.top}px;`,
        `    right: ${-inset.right}px;`,
        `    bottom: ${-inset.bottom}px;`,
        `    left: ${-inset.left}px;`,
        '}',
        ''
    );

    for (const [state, image] of Object.entries(asset.states)) {
        const url = `${ctx.assetDir}${image.src.split('/').pop()}`;
        const selector = `[${RUNTIME_ATTR.underlay}="${assetId}"][${RUNTIME_ATTR.state}="${state}"]`;
        const declarations: string[] = [];

        if (asset.mode === 'slice' && asset.sliceInsets && ctx.sliceImpl === 'border-image') {
            const css = cssInsets(asset.sliceInsets, asset.bakeScale);
            declarations.push(
                'border-style: solid;',
                'border-color: transparent;',
                `border-width: ${css.top}px ${css.right}px ${css.bottom}px ${css.left}px;`,
                `border-image-source: url("${url}");`,
                `border-image-slice: ${asset.sliceInsets.top} ${asset.sliceInsets.right} ${asset.sliceInsets.bottom} ${asset.sliceInsets.left} fill;`,
                `border-image-width: ${css.top}px ${css.right}px ${css.bottom}px ${css.left}px;`,
                'border-image-repeat: stretch;'
            );
        } else {
            declarations.push(
                `background-image: url("${url}");`,
                'background-repeat: no-repeat;',
                'background-size: 100% 100%;'
            );
        }

        // Variants are all present in the DOM from the first frame so the first hover never
        // waits on a texture upload; only their opacity changes.
        const isBase = state === 'base';
        declarations.push(`opacity: ${isBase ? 1 : 0};`);

        out.push(`${selector} {`, ...declarations.map((d) => `    ${d}`), '}', '');

        if (Object.keys(asset.states).length > 1) {
            out.push(
                `${selector}[${RUNTIME_ATTR.active}] { opacity: 1; }`,
                `[${RUNTIME_ATTR.underlay}="${assetId}"][${RUNTIME_ATTR.state}="base"]:not([${RUNTIME_ATTR.active}]) { opacity: 0; }`,
                ''
            );
        }
    }

    if (asset.mode === 'slice' && ctx.sliceImpl === 'divs' && asset.sliceInsets) {
        out.push(...nineDivRules(assetId, asset, ctx));
    }

    return out;
}

/**
 * §16.3, the fixed-box contract, expressed in CSS: each live part is pinned at the geometry
 * the layout engine gave it during the bake, at a fixed size, clipping anything that outgrows
 * it. There are no neighbours left to push.
 */
function livePartRules(assetId: string, asset: AssetEntry): string[] {
    const out: string[] = [];

    (asset.liveParts ?? []).forEach((part, index) => {
        out.push(
            `[${RUNTIME_ATTR.livePart}="${assetId}:${index}"] {`,
            '    position: absolute !important;',
            `    left: ${round(part.box.x - asset.borderWidths.left)}px;`,
            `    top: ${round(part.box.y - asset.borderWidths.top)}px;`,
            `    width: ${round(part.box.w)}px;`,
            `    height: ${round(part.box.h)}px;`,
            '    margin: 0 !important;',
            '    overflow: hidden;',
            '}',
            ''
        );
    });

    return out;
}

/** The nine-div fallback for engines whose border-image cannot be trusted. */
function nineDivRules(assetId: string, asset: AssetEntry, ctx: CssContext): string[] {
    const insets = asset.sliceInsets!;
    const base = asset.states.base;
    const scale = asset.bakeScale;

    const imageWidth = base.w / scale;
    const imageHeight = base.h / scale;
    const css = cssInsets(insets, scale);
    const middleWidth = imageWidth - css.left - css.right;
    const middleHeight = imageHeight - css.top - css.bottom;
    const url = `${ctx.assetDir}${base.src.split('/').pop()}`;

    const region = (name: string, rules: string[]) => [
        `[data-rz-slice="${assetId}:${name}"] {`,
        '    position: absolute;',
        `    background-image: url("${url}");`,
        '    background-repeat: no-repeat;',
        ...rules.map((r) => `    ${r}`),
        '}',
        '',
    ];

    // The edge and centre regions stretch the middle strip, so their background is scaled up
    // by the ratio between the region's own width and the strip's width in the sprite.
    const stretchX = `calc(100% * ${imageWidth} / ${middleWidth})`;
    const offsetX = `calc(-100% * ${css.left} / ${middleWidth})`;
    const stretchY = `calc(100% * ${imageHeight} / ${middleHeight})`;
    const offsetY = `calc(-100% * ${css.top} / ${middleHeight})`;

    return [
        ...region('tl', [`left: 0; top: 0; width: ${css.left}px; height: ${css.top}px;`, `background-size: ${imageWidth}px ${imageHeight}px;`, 'background-position: 0 0;']),
        ...region('tr', [`right: 0; top: 0; width: ${css.right}px; height: ${css.top}px;`, `background-size: ${imageWidth}px ${imageHeight}px;`, `background-position: ${-(imageWidth - css.right)}px 0;`]),
        ...region('bl', [`left: 0; bottom: 0; width: ${css.left}px; height: ${css.bottom}px;`, `background-size: ${imageWidth}px ${imageHeight}px;`, `background-position: 0 ${-(imageHeight - css.bottom)}px;`]),
        ...region('br', [`right: 0; bottom: 0; width: ${css.right}px; height: ${css.bottom}px;`, `background-size: ${imageWidth}px ${imageHeight}px;`, `background-position: ${-(imageWidth - css.right)}px ${-(imageHeight - css.bottom)}px;`]),
        ...region('t', [`left: ${css.left}px; right: ${css.right}px; top: 0; height: ${css.top}px;`, `background-size: ${stretchX} ${imageHeight}px;`, `background-position: ${offsetX} 0;`]),
        ...region('b', [`left: ${css.left}px; right: ${css.right}px; bottom: 0; height: ${css.bottom}px;`, `background-size: ${stretchX} ${imageHeight}px;`, `background-position: ${offsetX} ${-(imageHeight - css.bottom)}px;`]),
        ...region('l', [`left: 0; top: ${css.top}px; bottom: ${css.bottom}px; width: ${css.left}px;`, `background-size: ${imageWidth}px ${stretchY};`, `background-position: 0 ${offsetY};`]),
        ...region('r', [`right: 0; top: ${css.top}px; bottom: ${css.bottom}px; width: ${css.right}px;`, `background-size: ${imageWidth}px ${stretchY};`, `background-position: ${-(imageWidth - css.right)}px ${offsetY};`]),
        ...region('c', [`left: ${css.left}px; right: ${css.right}px; top: ${css.top}px; bottom: ${css.bottom}px;`, `background-size: ${stretchX} ${stretchY};`, `background-position: ${offsetX} ${offsetY};`]),
    ];
}

/**
 * Selectors that match a baked element both before and after the runtime has stamped it.
 *
 * The authored-attribute selector is a class selector, and a class selector matches any element
 * that *has* those classes, not only elements whose class list is exactly that. So a bake of
 * `div.panel` would also strip the decoration of a `div.panel.is-selected` that was baked
 * separately - including properties that element was deliberately keeping live. Where another bake
 * would be caught by this one, only the stamped id is used, and that element simply keeps its live
 * decoration for the one frame before the runtime attaches.
 */
function selectorsFor(assetId: string, manifest: RasterizeManifest): string[] {
    const selectors = [`[${RUNTIME_ATTR.id}="${assetId}"]`];

    const wouldCatchAnotherBake = (matcher: AssetMatcher) =>
        manifest.matchers.some(
            (other) =>
                other.assetId !== matcher.assetId &&
                other.tag === matcher.tag &&
                other.classes.length > matcher.classes.length &&
                matcher.classes.every((c) => other.classes.includes(c))
        );

    for (const matcher of manifest.matchers.filter((m) => m.assetId === assetId)) {
        if (matcher.authorId) {
            selectors.push(`[${ATTR.id}="${matcher.authorId}"]`);
        } else if (matcher.classes.length && !matcher.ambiguous && !wouldCatchAnotherBake(matcher)) {
            // Matching on the authored attribute too means the decoration is already stripped
            // when the document is parsed, instead of flashing for one frame. When an ancestor
            // class is what separates this bake from its lookalikes, it has to qualify the
            // selector too, or one asset's strip rule would fire on all of them.
            const own = `${matcher.tag}${matcher.classes.map((c) => `.${cssEscape(c)}`).join('')}[${ATTR.mark}]`;
            selectors.push(matcher.ancestorClass ? `.${cssEscape(matcher.ancestorClass)} ${own}` : own);
        }
    }

    return [...new Set(selectors)];
}

function cssInsets(insets: Insets, scale: number): Insets {
    return {
        top: round(insets.top / scale),
        right: round(insets.right / scale),
        bottom: round(insets.bottom / scale),
        left: round(insets.left / scale),
    };
}

const round = (n: number) => Math.round(n * 100) / 100;

function cssEscape(value: string): string {
    return value.replace(/([^\w-])/g, '\\$1');
}
