import { ATTR, RUNTIME_ATTR, type AssetEntry, type AssetMatcher, type Insets, type RasterizeManifest } from '../contract.js';

export interface CssContext {
    /** Asset directory relative to the emitted stylesheet. */
    assetDir: string;
}

/**
 * Every rule the pipeline emits lives in one stylesheet written at build time.
 *
 * It has to be a real stylesheet rather than styles applied at runtime: cohtml ignores `<style>`
 * elements appended after parse, so anything injected later would simply never apply.
 *
 * The decoration is drawn by a `::before` on the marked element rather than by a child element.
 * That is not a size optimisation, it is the only thing that works: cohtml re-resolves an
 * element's own style when its state changes but does not re-resolve its descendants', so a rule
 * reaching a child through `.btn:hover > .underlay` matches when it is asked and is never applied
 * when the state actually changes. A pseudo-element is part of the element's own style, so it
 * swaps correctly on `:hover`, `:active`, `:focus`, a class or an attribute - which is what lets
 * every state variant live in this file with no script in the page at all.
 */
export function emitStylesheet(manifest: RasterizeManifest, ctx: CssContext): string {
    const blocks: string[] = [
        '/* Generated by vite-gameface-rasterize. Do not edit - it is rewritten on every build. */',
        '',
    ];

    for (const [assetId, asset] of Object.entries(manifest.assets)) {
        blocks.push(...stripRules(assetId, asset, manifest));
        blocks.push(...decorationRules(assetId, asset, manifest, ctx));
        if (asset.mode === 'element') blocks.push(...livePartRules(assetId, asset));
    }

    return blocks.join('\n') + '\n';
}

/**
 * Turns off the properties that are now in the texture. This runs against the final computed
 * set through an attribute selector rather than by editing the author's own rules, so
 * specificity never has to be reasoned about and the source CSS stays readable.
 */
function stripRules(assetId: string, asset: AssetEntry, manifest: RasterizeManifest): string[] {
    const declarations: string[] = [];

    for (const property of asset.strippedProperties) {
        switch (property) {
            case 'box-shadow':
                declarations.push('box-shadow: none !important;');
                break;
            case 'background-image':
                declarations.push('background-image: none !important;');
                break;
            case 'background-color':
                declarations.push('background-color: transparent !important;');
                break;
            case 'border-radius':
                declarations.push('border-radius: 0 !important;');
                break;
            case 'border-color':
                // The width stays: it is layout, and dropping it would move everything inside.
                declarations.push('border-color: transparent !important;');
                break;
            case 'border-image-source':
                declarations.push('border-image-source: none !important;');
                break;
            case 'filter':
                declarations.push('filter: none !important;');
                break;
            case 'mask-image':
                declarations.push('mask-image: none !important;');
                break;
        }
    }

    // Element mode empties the element: everything static became the texture, and the live parts
    // that remain are absolutely positioned. An element whose height came from those children now
    // has nothing holding it open and collapses to its padding, taking the underlay with it - so
    // the size it was captured at is pinned here. That is the fixed-box contract stated in CSS:
    // the subtree's geometry was decided at build time.
    if (asset.mode === 'element') {
        declarations.push('box-sizing: border-box;');
        declarations.push(`width: ${round(asset.captureSize.w)}px;`);
        declarations.push(`height: ${round(asset.captureSize.h)}px;`);
    }

    // The decoration is an absolutely positioned pseudo-element, so the element has to be its
    // containing block.
    //
    // `relative` is only correct for an element that was static. These rules are matched by
    // `div.class[data-rasterize]`, which outranks the plain `.class` selector the author
    // wrote, so emitting it unconditionally would drop every absolutely positioned decoration
    // back into flow - and in a HUD, corner-pinned panels are most of them. Any value other
    // than `static` already establishes a containing block, which is all that is needed.
    //
    // The pseudo-element is painted at `z-index: -1` so it lands between the element's own
    // background and its text, which is where a decoration belongs. An absolutely positioned
    // pseudo-element with `z-index: auto` paints *after* in-flow content and would cover the
    // text instead. The negative index only stays inside this element if the element is a
    // stacking context, so one is forced here; without it the decoration escapes upwards and is
    // painted behind whatever ancestor background happens to be opaque.
    if ((asset.position ?? 'static') === 'static') declarations.push('position: relative;');
    declarations.push('z-index: 0;');

    return [`${selectorsFor(assetId, manifest).join(',\n')} {`, ...declarations.map((d) => `    ${d}`), '}', ''];
}

/**
 * The decoration itself, as a `::before` on the marked element.
 *
 * The base state carries the box - where the pseudo-element sits and how the texture fills it -
 * and each variant then changes only the image, because everything else about it is identical.
 * Variants are emitted in declared order and all carry the same specificity, so a later state
 * beats an earlier one purely by source order: a pressed button that is also hovered reads as
 * active, which is the rule the old JavaScript implemented by scanning the state list forwards.
 */
function decorationRules(assetId: string, asset: AssetEntry, manifest: RasterizeManifest, ctx: CssContext): string[] {
    const out: string[] = [];
    const { inkOverflow, borderWidths } = asset;

    // An absolutely positioned box is placed against its parent's padding box, so reaching the
    // border box edge means offsetting by the border width as well as the ink overflow.
    const inset: Insets = {
        top: inkOverflow.top + borderWidths.top,
        right: inkOverflow.right + borderWidths.right,
        bottom: inkOverflow.bottom + borderWidths.bottom,
        left: inkOverflow.left + borderWidths.left,
    };

    const roots = paintSelectorsFor(assetId, manifest);
    const at = (state: string) => {
        const pseudo = stateSelector(state);
        return roots.map((root) => `${root}${pseudo ?? ''}::before`).join(',\n');
    };

    for (const [state, image] of Object.entries(asset.states)) {
        const url = `${ctx.assetDir}${image.src.split('/').pop()}`;
        const isBase = state === 'base';
        if (!isBase && !stateSelector(state)) continue;

        const declarations: string[] = [];

        if (isBase) {
            declarations.push(
                // Without content the pseudo-element is not generated at all.
                "content: '';",
                'position: absolute;',
                'display: block;',
                'pointer-events: none;',
                // Between the element's background and its text. See the note in stripRules.
                'z-index: -1;',
                `top: ${-inset.top}px;`,
                `right: ${-inset.right}px;`,
                `bottom: ${-inset.bottom}px;`,
                `left: ${-inset.left}px;`
            );
        }

        if (asset.mode === 'slice' && asset.sliceInsets) {
            const css = cssInsets(asset.sliceInsets, asset.bakeScale);
            if (isBase) {
                declarations.push(
                    'border-style: solid;',
                    'border-color: transparent;',
                    `border-width: ${css.top}px ${css.right}px ${css.bottom}px ${css.left}px;`,
                    `border-image-slice: ${asset.sliceInsets.top} ${asset.sliceInsets.right} ${asset.sliceInsets.bottom} ${asset.sliceInsets.left} fill;`,
                    `border-image-width: ${css.top}px ${css.right}px ${css.bottom}px ${css.left}px;`,
                    'border-image-repeat: stretch;'
                );
            }
            declarations.push(`border-image-source: url("${url}");`);
        } else {
            if (isBase) declarations.push('background-repeat: no-repeat;', 'background-size: 100% 100%;');
            declarations.push(`background-image: url("${url}");`);
        }

        out.push(`${at(state)} {`, ...declarations.map((d) => `    ${d}`), '}', '');
    }

    // See buttonSelectorsFor: cohtml places a pseudo-element's left edge at a `<button>`'s own
    // edge whatever the offset says, so the shift is put back by hand for those and only those.
    const buttons = buttonSelectorsFor(assetId, manifest);
    if (buttons.length && inset.left) {
        out.push(
            `${buttons.map((root) => `${root}::before`).join(',\n')} {`,
            `    transform: translateX(${-inset.left}px);`,
            '}',
            ''
        );
    }

    return out;
}

/**
 * The CSS a state variant is selected by, on the marked element itself.
 *
 * Every one of these is a condition on the element, never on a descendant, which is what makes
 * the swap actually happen: cohtml re-resolves an element and its pseudo-elements when its own
 * state changes, and does not re-resolve its children.
 */
function stateSelector(state: string): string | null {
    if (state === 'base') return null;
    if (state === 'hover') return ':hover';
    if (state === 'active') return ':active';
    if (state === 'focus') return ':focus';
    if (state === 'disabled') return '[disabled]';
    if (state.indexOf('class:') === 0) return `.${cssEscape(state.slice(6))}`;
    return null;
}

/**
 * §16.3, the fixed-box contract, expressed in CSS: each live part is pinned at the geometry
 * the layout engine gave it during the bake, at a fixed size, clipping anything that outgrows
 * it. There are no neighbours left to push.
 */
function livePartRules(assetId: string, asset: AssetEntry): string[] {
    const out: string[] = [];

    (asset.liveParts ?? []).forEach((part, index) => {
        out.push(
            `[${RUNTIME_ATTR.livePart}="${assetId}:${index}"] {`,
            '    position: absolute !important;',
            `    left: ${round(part.box.x - asset.borderWidths.left)}px;`,
            `    top: ${round(part.box.y - asset.borderWidths.top)}px;`,
            `    width: ${round(part.box.w)}px;`,
            `    height: ${round(part.box.h)}px;`,
            '    margin: 0 !important;',
            '    overflow: hidden;',
            '}',
            ''
        );
    });

    return out;
}

/**
 * Selectors that match a baked element both before and after the runtime has stamped it.
 *
 * The authored-attribute selector is a class selector, and a class selector matches any element
 * that *has* those classes, not only elements whose class list is exactly that. So a bake of
 * `div.panel` would also strip the decoration of a `div.panel.is-selected` that was baked
 * separately - including properties that element was deliberately keeping live. Where another bake
 * would be caught by this one, only the stamped id is used, and that element simply keeps its live
 * decoration for the one frame before the runtime attaches.
 */
/**
 * Selectors that find an asset's elements in a document the runtime has not touched yet.
 *
 * This is the same set the stylesheet paints through, minus the stamped-id selector - which
 * matches nothing until the element has been claimed - and plus the recorded document position
 * for a bake that nothing else separates. The runtime hands these straight to
 * `querySelectorAll`, which is why it needs no matcher of its own.
 *
 * Unlike {@link selectorsFor} this deliberately keeps a selector that would also catch a more
 * specific bake. Dropping it there protects the strip rules from over-applying; dropping it here
 * would leave the general bake's own elements with no way to be found at all. Over-matching is
 * handled instead by ordering the payload most-specific-first and letting the first claim win.
 */
export function matchSelectorsFor(assetId: string, manifest: RasterizeManifest): string[] {
    return [...new Set(matchEntriesFor(assetId, manifest).map((e) => e.sel))];
}

/** The same selectors, each still paired with the tag it was built from. */
function matchEntriesFor(assetId: string, manifest: RasterizeManifest): { sel: string; tag: string }[] {
    const selectors: { sel: string; tag: string }[] = [];

    for (const matcher of manifest.matchers.filter((m) => m.assetId === assetId)) {
        const push = (sel: string) => selectors.push({ sel, tag: matcher.tag });

        if (matcher.authorId) {
            push(`[${ATTR.id}="${cssEscape(matcher.authorId)}"]`);
        } else if (matcher.ambiguous || !matcher.classes.length) {
            // Nothing separates it by class - either because its key is shared, or because it has
            // no classes at all - so document position is what is left. The path is recorded in
            // `tag:nth-of-type(n)` form, which is already a valid selector.
            //
            // A classless bake must not fall back to its tag: `div[data-rasterize]` would match
            // every marked div on the page and hand them all one element's texture.
            if (matcher.selectorPath) push(matcher.selectorPath);
        } else {
            const own = `${matcher.tag}${matcher.classes.map((c) => `.${cssEscape(c)}`).join('')}[${ATTR.mark}]`;
            push(matcher.ancestorClass ? `.${cssEscape(matcher.ancestorClass)} ${own}` : own);
        }
    }

    return selectors;
}

/**
 * Selectors whose element is a `<button>`, which needs the decoration nudged back into place.
 *
 * cohtml drops the horizontal offset of an absolutely positioned pseudo-element inside a
 * `<button>`: the width resolves correctly and the vertical offsets do, but `left: -26px` places
 * the box at the button's own left edge instead of 26px outside it. A `translateX` of the same
 * amount puts it back, and is applied to nothing else, because on any other element it would
 * shift a correctly placed box.
 */
function buttonSelectorsFor(assetId: string, manifest: RasterizeManifest): string[] {
    const entries = matchEntriesFor(assetId, manifest);
    const buttons = entries.filter((e) => e.tag === 'button');
    if (!buttons.length) return [];

    // The stamped id carries no tag, so it only joins the group when nothing else could match.
    const stamped = entries.length === buttons.length ? [`[${RUNTIME_ATTR.id}="${assetId}"]`] : [];

    return [...new Set([...stamped, ...buttons.map((e) => e.sel)])];
}

/** How specific an asset's match is, for ordering the runtime payload. */
export function matchSpecificity(assetId: string, manifest: RasterizeManifest): number {
    return manifest.matchers
        .filter((m) => m.assetId === assetId)
        .reduce(
            (max, m) =>
                // A position selector identifies exactly one element, so it is the most specific
                // thing there is and must claim before any class selector reaches that element.
                Math.max(max, m.authorId ? 1000 : m.ambiguous || !m.classes.length ? 500 : m.classes.length),
            0
        );
}

/**
 * Selectors the underlay rules are scoped through.
 *
 * Paint is not strip: where two bakes both match an element, both sets of underlay rules apply and
 * the longer class list wins on specificity, which is the same "longest match" answer the runtime
 * used to compute by hand. So this keeps every selector, including the ones {@link selectorsFor}
 * has to drop, and adds the stamped id for elements the HTML injector reached.
 */
export function paintSelectorsFor(assetId: string, manifest: RasterizeManifest): string[] {
    return [...new Set([`[${RUNTIME_ATTR.id}="${assetId}"]`, ...matchSelectorsFor(assetId, manifest)])];
}

function selectorsFor(assetId: string, manifest: RasterizeManifest): string[] {
    const selectors = [`[${RUNTIME_ATTR.id}="${assetId}"]`];
    const mine = manifest.assets[assetId];

    // Over-matching only does harm when this bake turns off a property the longer bake was
    // keeping live; where the longer bake strips everything this one does, the extra elements it
    // catches were going to have those properties stripped anyway and the selector can stay.
    const wouldCatchAnotherBake = (matcher: AssetMatcher) =>
        manifest.matchers.some((other) => {
            if (other.assetId === matcher.assetId) return false;
            if (other.tag !== matcher.tag) return false;
            if (other.classes.length <= matcher.classes.length) return false;
            if (!matcher.classes.every((c) => other.classes.includes(c))) return false;

            const theirs = new Set(manifest.assets[other.assetId]?.strippedProperties ?? []);
            return (mine?.strippedProperties ?? []).some((property) => !theirs.has(property));
        });

    for (const matcher of manifest.matchers.filter((m) => m.assetId === assetId)) {
        if (matcher.authorId) {
            selectors.push(`[${ATTR.id}="${matcher.authorId}"]`);
        } else if (matcher.classes.length && !matcher.ambiguous && !wouldCatchAnotherBake(matcher)) {
            // Matching on the authored attribute too means the decoration is already stripped
            // when the document is parsed, instead of flashing for one frame. When an ancestor
            // class is what separates this bake from its lookalikes, it has to qualify the
            // selector too, or one asset's strip rule would fire on all of them.
            const own = `${matcher.tag}${matcher.classes.map((c) => `.${cssEscape(c)}`).join('')}[${ATTR.mark}]`;
            selectors.push(matcher.ancestorClass ? `.${cssEscape(matcher.ancestorClass)} ${own}` : own);
        }
    }

    return [...new Set(selectors)];
}

function cssInsets(insets: Insets, scale: number): Insets {
    return {
        top: round(insets.top / scale),
        right: round(insets.right / scale),
        bottom: round(insets.bottom / scale),
        left: round(insets.left / scale),
    };
}

const round = (n: number) => Math.round(n * 100) / 100;

function cssEscape(value: string): string {
    return value.replace(/([^\w-])/g, '\\$1');
}
