export interface RuntimeAsset {
    /** The asset this entry flattens. */
    id: string;
    /**
     * Selector list that finds the marked elements, the same one the stylesheet paints through.
     *
     * Matching is the engine's job, not this file's: a class selector already means "has these
     * classes", so `querySelectorAll` answers the question the old hand-written matcher spent
     * eighty lines approximating.
     */
    sel: string;
    /** Child-index paths of the nodes that must survive flattening, in emission order. */
    liveParts: number[][];
}

export interface RuntimePayload {
    /** Element-mode assets only. Everything else is drawn by the stylesheet alone. */
    assets: RuntimeAsset[];
    /** Re-scan on DOM insertion. Off by default; see the `runtime` option. */
    observe: boolean;
}

/**
 * The last piece of JavaScript this plugin can ship, and most builds do not ship it.
 *
 * Decorations need nothing here: they are drawn by a `::before` on the marked element, matched
 * and swapped entirely by the emitted stylesheet. Element mode is the exception, because
 * flattening deletes the wrapper nodes and CSS can hide a node but not remove one.
 *
 * The build already flattens every element-mode subtree it can find in an HTML file. What is left
 * is a subtree a framework builds when the app runs, which no file contains and no build-time
 * rewrite can reach. This flattens those, once, at DOMContentLoaded, and then stops.
 */
function rzRuntime(payload: RuntimePayload): void {
    var ID = 'data-rz-id';
    var LIVE = 'data-rz-live';

    function resolvePath(root: Element, path: number[]): Element | null {
        var node: Element | null = root;
        for (var i = 0; i < path.length && node; i++) node = node.children[path[i]] || null;
        return node;
    }

    /**
     * The wrapper hierarchy did its job at build time. Everything static is now in the texture,
     * so the wrappers are removed and the live parts are re-attached directly to the flattened
     * container, where the stylesheet pins them at their captured geometry.
     */
    function flatten(el: Element, asset: RuntimeAsset): void {
        var live: Element[] = [];

        // Resolve every path before detaching anything: removing a node renumbers its siblings.
        for (var i = 0; i < asset.liveParts.length; i++) {
            var node = resolvePath(el, asset.liveParts[i]);
            if (node) live.push(node);
        }

        for (var j = 0; j < live.length; j++) {
            if (live[j].parentNode) live[j].parentNode!.removeChild(live[j]);
        }

        while (el.firstChild) el.removeChild(el.firstChild);

        for (var k = 0; k < live.length; k++) {
            live[k].setAttribute(LIVE, asset.id + ':' + k);
            el.appendChild(live[k]);
        }

        el.setAttribute(ID, asset.id);
    }

    function sweep(root: ParentNode): void {
        // querySelectorAll only looks at descendants, so a marked element that is itself the
        // root of an inserted subtree has to be tested separately or it is never claimed.
        var self = (root as Node).nodeType === 1 ? (root as Element) : null;

        for (var i = 0; i < payload.assets.length; i++) {
            var asset = payload.assets[i];
            if (self && self.matches && self.matches(asset.sel) && !self.hasAttribute(ID)) flatten(self, asset);

            var found = root.querySelectorAll(asset.sel);
            for (var j = 0; j < found.length; j++) {
                if (!found[j].hasAttribute(ID)) flatten(found[j], asset);
            }
        }
    }

    function start(): void {
        sweep(document);

        if (!payload.observe) return;

        // Opt-in only. Attributes are deliberately not watched: nothing here depends on a class,
        // so the only thing left that needs a hand is a subtree that did not exist at boot.
        var observer = new MutationObserver(function (records) {
            for (var i = 0; i < records.length; i++) {
                var added = records[i].addedNodes;
                for (var j = 0; j < added.length; j++) {
                    if (added[j].nodeType === 1) sweep(added[j] as Element);
                }
            }
        });

        observer.observe(document.documentElement, { childList: true, subtree: true });
    }

    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start);
    else start();
}

/** Serialises the runtime with its payload baked in - no fetch, no manifest request at boot. */
export function buildRuntime(payload: RuntimePayload): string {
    return [
        '/* Generated by vite-gameface-rasterize. Do not edit - it is rewritten on every build. */',
        `;(${rzRuntime.toString()})(${JSON.stringify(payload)});`,
        '',
    ].join('\n');
}
